### ISSUE TITLE
Can produce incompatible Openformats models on export...

### ISSUE THREAD

**Issue by 3941** [lucasvinbr/blender_io_GTA5Ped#1]
Hi,

I've been experimenting with your plugin and I've created perfectly working models with it, but I also ran into seemingly random problems.

I've created a piece of clothing or rather a whole UPPR for a ped model almost from scratch and I got it working, but it needs some weights readjustments and it almost seems random that the export works, or doesn't, sometimes... Though once it fails I basically need to go back to a working version... I was never able to "repair" a version that would fail.

The error I get in OpenIV is: Incorrect vertex component count. Expected: <something>, Actual: <something higher>

I have no clue what that even means, or why it happens.
I can probably provide you with blender files and resulting outputs, if you care to take a look. It's been a few weeks I've last been working on this, because I got so frustrated I dropped it. I don't even know if you plan to actively work on this at all, but if you are, I'll gladly work with you and provide what's needed to figure this out.

Thanks for looking at my issue, if you are, that is.

**Comment by lucasvinbr** [comment]
Hi,

Is it a piece of clothing for a streamed ped or a "normal" one?

If possible, please do send the files hehe.

**Comment by 3941** [comment]
Man, I'm so sorry I completely missed your response that day.
I just checked my emails and there it is. I dunno how I missed it. I probably didn't expect one so soon.

It's a ped-ped, not a streamed/player one.

I prepared some files for you to look at: \<redacted\> 😉 

So, there are two folders, working and not working, the only difference between those, except for the .blend file, is the jbib_01_high.mesh . And the only difference inbetween those blender files is that I changed some weight paints on that specific mesh and kept exporting until the import in OpenIV broke. Namely weights of SKEL_Spine3, SKEL_Head, RB_LThigRoll and RB_RThigRoll. In OpenIV, just import the whole model fourtee_test.odd.

That proved to be quite frustrating while modeling that thing, because I had to fix weights and it just randomly kept breaking (at least that's how I perceived it). I wasn't able to produce a final version I was happy with in game.

Don't worry about funky looking texturing of the model in OpenIV. UV mappings only work properly in GTA5 if you split models at the seams of UV islands, which is something I was planning to do for the final export, and not bother with until I'm done with all the other details.
(That would be a really nice feature for your export plugin to have, though... maybe there's a simple way to automate it? I've found scripts for blender to do that, but never got them to work.)

**Comment by lucasvinbr** [comment]
Hey! So, I finally had a look at the files (sorry for the delay), and indeed it's a problem with how the plugin was exporting weights. The good news is I could only reproduce the issue with an older version of this plugin; version 0.0.5 seems to properly limit weights. The not working version was imported successfully in OpenIV after exporting with 0.0.5.

So, I recommend installing the latest version of this plugin, closing and reopening Blender (mine was still exporting incorrectly before closing) and trying again; hopefully it should work hehe.

About the texturing, good news too: the islands looked fine in the "fixed" not working version! The plugin does have some stuff attempting to handle the UV islands like you mentioned... I think they were broken too hahahah

**Comment by 3941** [comment]
I wasn't even aware there's a newer version!!!
Maybe you should use the release thingy that's provided by github?
I dunno... I'll still figure it out, though. Thank you very much for looking at it.

Do you even realise you're the rainbow colored unicorn of the GTA5 modding scene? And barely anyone noticed you, yet.
It's either 3dsmax and a very, very broken plugin (I could export working models on that as long as I didn't change anything, but it was also splitting meshes into countless parts, making them have 10 times more vertices than necessary. Also I could never make a custom model actually get weighted properly).
Ooor it's a paid for, proprietary program that works just fine but has very, very awkward workflow.
The whole GTA5 modding scene is a pain when it comes to collecting information on how to do things...

So you're making something SUPER SPECIAL here.
Were you aware of this plugin? https://github.com/LendoK/Blender_GTA_V_model_importer
I like to do this one first, so it creates materials for me to work with, before importing the model with your plugin.
It also seems to get the bones correct (unless you already fixed that, too...)

Anyway, I'm very thankful for you looking into it, and pointing me to a new version I wasn't even aware of.
You're fucking GTA5 modding Jesus to me!

**Comment by lucasvinbr** [comment]
hahahah thank you for the kind words! I've added a release link for 0.0.6, the latest version.

Yeah, I haven't figured out the bones yet, but that plugin looks really good hehe. I'll have a look

**Comment by 3941** [comment]
I just updated and apparently I was still on version 0.0.2. No wonder I had issues.
It'll be fun to return to that little hobby project now.
Anyway, I think it's appropriate to close this issue, right? So that's what I'll do.
I'll keep close watch on updates, though 😄 
Thank you so much for your work on this!
