### ISSUE TITLE
Small issue when exporting the mesh

### ISSUE THREAD

**Issue by siaxace** [lucasvinbr/blender_io_GTA5Ped#2]
Hi, I've been experimenting with your plugin quite a bit and it works mostly fine. One issue I had was after importing a model (in my case the mp_female), the bones, materials and UV mappings, well almost everything gets imported just fine but after exporting the mesh, and loading it in game, the tattoos get mapped out of the place. I've not been able to make head or tails of why this really is happening? The textures and everything looks good except for the tattoos. I'd appreciate if you could guide me on this one.

**Comment by siaxace** [comment]
Just taking a quick look at your code "export_mesh.py", I noticed something in one of the lines (#146): 

`parse_iterableFloatData(geom.uvCoords[i]),` #second UV map... we don't use it for now

So I think that might be reason for the weird mapping of the tattoos? (The second UV map) 
Then again I might be wrong but be glad to hear from you.

**Comment by lucasvinbr** [comment]
Hi there! So, could you please tell me more about your process, like, which file did you export to ODD, how you were exporting and stuff?

**Comment by lucasvinbr** [comment]
> 
> 
> Just taking a quick look at your code "export_mesh.py", I noticed something in one of the lines (#146):
> 
> `parse_iterableFloatData(geom.uvCoords[i]),` #second UV map... we don't use it for now
> 
> So I think that might be reason for the weird mapping of the tattoos? (The second UV map)
> Then again I might be wrong but be glad to hear from you.

Yeah, it's a possibility... I haven't tried importing the mp models though. Which file(s) did you import?

**Comment by siaxace** [comment]
So basically for my work, I used the "uppr_015_r.ydd", from female multiplayer characters (which would be a streamed ped I believe). And then with the help of OpenIV and your plugin I imported it into the Blender. After doing a little bit of sculpting I exported the mesh, with High Opaque (S12D0183F) and starting shader set to '0' for the options. 

Then I simply replaced the exported mesh with the "uppr_015_r_high.mesh" inside the folder of .odd file. And from there it was pretty straight forward, I merely imported the modified .odd file into the OpenIV.

**Comment by siaxace** [comment]
And I also have to say this, because I did play around with the UV mappings and it really feels like there is second UV mapping involved in mp characters. Well to put simply I did find the mapping where the tattoos get mapped correctly on the character, but when I use that mapping, the textures would look weird and out of place. So most probably that is the issue here.

**Comment by lucasvinbr** [comment]
Hey! So, I've tried to add support for a second UV layer. I've tried importing an "uppr_015_r.ydd" I found with OpenIV and it appears to have brought two UVs. Exporting seems to have kept the data too. Please try again with this new version; I hope it works hehe

**Comment by siaxace** [comment]
Hey there Lucas,

It's me again, I had to write to you on email because there are some issues
I still have with the plugin that I need to ask you about with more details.

Well first and foremost, I love your work. It's amazing but sadly I've not
resolved the problem with the second UV later. As you already know, the
second layer is responsible for the mapping of tattoos and  I've attached a
screenshot from my second UVchannel from the blender workspace:

https://imgur.com/a/mKy8wHN

The first layer works as intended and it's all fine but since you've
mentioned in your comments that you've got it working, I was wondering if
you could share a screenshot from your second UVchannel.

I really appreciate the time and effort that you've put into this.
Sincerely,
Siaxace

**Comment by siaxace** [comment]
Hey again,

Nevermind what I said, your plugin works just fine and the error was on my
side.

**Comment by siaxace** [comment]
Hey! 
Yes I've tried it and the export function works as intended. Thanks again.
